# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: splan

before:
  hooks:
    - go mod tidy

builds:
  - id: splan
    main: ./cmd/splan
    binary: splan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

brews:
  - name: splan
    repository:
      owner: grokify
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/grokify/structured-plan"
    description: "CLI for structured planning documents (PRD, MRD, TRD, OKR, V2MOM)"
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore(formula): update {{ .ProjectName }} to {{ .Version }}"
    install: |
      bin.install "splan"
    test: |
      system "#{bin}/splan", "--version"

release:
  github:
    owner: grokify
    name: structured-plan
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
